import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Inter,
    JetBrains_Mono,
    Nunito,
} from "next/font/google";
import { PropsWithChildren } from "react";

import { ConvexClientProvider } from "@/components/provider/ConvexClientProvider";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const sansFont = Nunito({
    variable: "--font-sans",
    subsets: ["latin"],
});

const monoFont = JetBrains_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="en" className={inter.variable}>
                <body
                    className={cn(
                        "antialiased",
                        sansFont.variable,
                        monoFont.variable,
                    )}
                >
                    <ConvexClientProvider>{children}</ConvexClientProvider>
                </body>
            </html>
        </ConvexAuthNextjsServerProvider>
    );
}
