import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/ui/themes";
import type { Metadata } from "next";
import { JetBrains_Mono, Nunito } from "next/font/google";
import { PropsWithChildren } from "react";

import { ConvexClientProvider } from "@/components/provider/ConvexClientProvider";
import { cn } from "@/lib/utils";

import "./globals.css";

const sansFont = Nunito({
    variable: "--font-sans",
    subsets: ["latin"],
});

const monoFont = JetBrains_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en" className="dark" suppressHydrationWarning>
            <body
                className={cn(
                    "antialiased",
                    sansFont.variable,
                    monoFont.variable,
                )}
            >
                <ClerkProvider appearance={{ theme: shadcn }}>
                    <ConvexClientProvider>{children}</ConvexClientProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
